### ISSUE TITLE
flash of unstyled content when loading

### ISSUE THREAD

**Issue by eads** [thechicagoreporter/electoraid#3]
THE DREADED FOUC

**Comment by eads** [comment]
fixed in 93b2a0f8cad

@designhawg (hopefully you get pinged with this) -- installing the gatsby plugin for styled components is required to make the server side rendering work right

**Comment by eads** [comment]
fixed in 93b2a0f8cad

@designhawg (hopefully you get pinged with this) -- installing the gatsby plugin for styled components is required to make the server side rendering work right

**Comment by designhawg** [comment]
Hey there. Styled-components is required, so your hunch is correct. Sorry for the lack of communication on that item.
